services:
  amplify-dev:  
    build:
      context: ./amplify-cli/
      target: dev
    ports:
      - "3000:3000"  
    volumes:
      - C:\Users\eortiz\vscode\amplify\amplify-landing-pre-register:/app
    restart: always
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 